### ISSUE TITLE
Insite Rebranding

### ISSUE THREAD

**Issue by Pr0x1m4** [PalisadoesFoundation/garnet#59]
Choose one: feature request?

When Garnet was first split off from `infosetDB` it was thought to be a separate entity, while this is still the case, I've talked with @caribbeanyute and @Jhamali and have decided a that rebranding and restructuring of the frontend is necessary to make the interface more cohesive and inline with `infoset`'s overall theme. Thus we've decided to rename and rebranding `garnet` and `garnet-ui` as `insite` and `insite-ui` respectfully.

### Possible Solution
- [ ] Create Sidebar Navigation
- [ ] Create LineChart Component
- [ ] Create Pie Chart Component
- [ ] Create Process List Component
- [ ] Create New Machine Dialog/Button
- [ ] Create Avatar Component

I've attached the respective figma board of the proposed design of insite here: https://www.figma.com/file/dDWjQgqxF2TkxDFHe7j5AmCC/insite?node-id=0%3A1

### Screenshots

![group 4 1](https://user-images.githubusercontent.com/4820517/44623112-a3b16580-a88c-11e8-9e6d-4d2ff464b1e5.png)

**Comment by Pr0x1m4** [comment]
Starting with renaming the repo first :tada:

**Comment by Pr0x1m4** [comment]
Update!
![2019-07-14-214951_3000x1080_scrot](https://user-images.githubusercontent.com/4820517/61194081-ec306800-a684-11e9-87d8-9f77620eed29.png)
